import { createGalleryImageAsset, createGalleryManifest } from "@/lib/content/builders";

const emulsioneImages = [
  createGalleryImageAsset({
    id: "emulsione-01",
    index: 1,
    filename: "img1.jpg",
    publicPath: "/media/emulsione/img1.jpg",
    legacyPath: "emulsione/img/img1.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a pale green shoreline and sand blocks under a bright sky.",
  }),
  createGalleryImageAsset({
    id: "emulsione-02",
    index: 2,
    filename: "img2.jpg",
    publicPath: "/media/emulsione/img2.jpg",
    legacyPath: "emulsione/img/img2.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a blocky cliff descending into dark blue water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-03",
    index: 3,
    filename: "img3.jpg",
    publicPath: "/media/emulsione/img3.jpg",
    legacyPath: "emulsione/img/img3.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of blue water with a tree-lined shore in the distance.",
  }),
  createGalleryImageAsset({
    id: "emulsione-04",
    index: 4,
    filename: "img4.jpg",
    publicPath: "/media/emulsione/img4.jpg",
    legacyPath: "emulsione/img/img4.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a small island beyond a stepped sandy shoreline.",
  }),
  createGalleryImageAsset({
    id: "emulsione-05",
    index: 5,
    filename: "img5.jpg",
    publicPath: "/media/emulsione/img5.jpg",
    legacyPath: "emulsione/img/img5.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a bright horizon above a grassy slope beside water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-06",
    index: 6,
    filename: "img6.jpg",
    publicPath: "/media/emulsione/img6.jpg",
    legacyPath: "emulsione/img/img6.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a river bend bordered by grass and trees.",
  }),
  createGalleryImageAsset({
    id: "emulsione-07",
    index: 7,
    filename: "img7.jpg",
    publicPath: "/media/emulsione/img7.jpg",
    legacyPath: "emulsione/img/img7.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a desert plain with two cactus blocks under a pale sky.",
  }),
  createGalleryImageAsset({
    id: "emulsione-08",
    index: 8,
    filename: "img8.jpg",
    publicPath: "/media/emulsione/img8.jpg",
    legacyPath: "emulsione/img/img8.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of stepped sand cliffs beside calm water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-09",
    index: 9,
    filename: "img9.jpg",
    publicPath: "/media/emulsione/img9.jpg",
    legacyPath: "emulsione/img/img9.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a lone tree on a thin strip of land beside blue water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-10",
    index: 10,
    filename: "img10.jpg",
    publicPath: "/media/emulsione/img10.jpg",
    legacyPath: "emulsione/img/img10.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a grassy field with a blocky hill and scattered trees.",
  }),
  createGalleryImageAsset({
    id: "emulsione-11",
    index: 11,
    filename: "img11.jpg",
    publicPath: "/media/emulsione/img11.jpg",
    legacyPath: "emulsione/img/img11.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of two small islands above deep blue water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-12",
    index: 12,
    filename: "img12.jpg",
    publicPath: "/media/emulsione/img12.jpg",
    legacyPath: "emulsione/img/img12.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a snowy shoreline with a dark tree silhouette.",
  }),
  createGalleryImageAsset({
    id: "emulsione-13",
    index: 13,
    filename: "img13.jpg",
    publicPath: "/media/emulsione/img13.jpg",
    legacyPath: "emulsione/img/img13.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a sandy riverbank with trees and blocky clouds.",
  }),
  createGalleryImageAsset({
    id: "emulsione-14",
    index: 14,
    filename: "img14.jpg",
    publicPath: "/media/emulsione/img14.jpg",
    legacyPath: "emulsione/img/img14.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a grassy shoreline with trees and a blue inlet.",
  }),
  createGalleryImageAsset({
    id: "emulsione-15",
    index: 15,
    filename: "img15.jpg",
    publicPath: "/media/emulsione/img15.jpg",
    legacyPath: "emulsione/img/img15.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of stepped block hills beneath a floating land mass.",
  }),
  createGalleryImageAsset({
    id: "emulsione-16",
    index: 16,
    filename: "img16.jpg",
    publicPath: "/media/emulsione/img16.jpg",
    legacyPath: "emulsione/img/img16.jpg",
    width: 2048,
    height: 2560,
    alt: "Polaroid print of a sandy shore with a pyramid-like hill and trees.",
  }),
  createGalleryImageAsset({
    id: "emulsione-17",
    index: 17,
    filename: "img17.jpg",
    publicPath: "/media/emulsione/img17.jpg",
    legacyPath: "emulsione/img/img17.jpg",
    width: 2560,
    height: 2560,
    alt: "Damaged emulsion transfer of a pale green shoreline split by vertical cracks.",
  }),
  createGalleryImageAsset({
    id: "emulsione-18",
    index: 18,
    filename: "img18.jpg",
    publicPath: "/media/emulsione/img18.jpg",
    legacyPath: "emulsione/img/img18.jpg",
    width: 2560,
    height: 2560,
    alt: "Borderless damaged print of a green shoreline above violet water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-19",
    index: 19,
    filename: "img19.jpg",
    publicPath: "/media/emulsione/img19.jpg",
    legacyPath: "emulsione/img/img19.jpg",
    width: 2560,
    height: 2560,
    alt: "Distorted film print of a lone tree beside a yellow field.",
  }),
  createGalleryImageAsset({
    id: "emulsione-20",
    index: 20,
    filename: "img20.jpg",
    publicPath: "/media/emulsione/img20.jpg",
    legacyPath: "emulsione/img/img20.jpg",
    width: 2560,
    height: 2560,
    alt: "Burned and curled film fragment showing a blocky building beside blue water.",
  }),
  createGalleryImageAsset({
    id: "emulsione-21",
    index: 21,
    filename: "img21.jpg",
    publicPath: "/media/emulsione/img21.jpg",
    legacyPath: "emulsione/img/img21.jpg",
    width: 2560,
    height: 2560,
    alt: "Crumpled orange-toned emulsion transfer with small landscape fragments.",
  }),
  createGalleryImageAsset({
    id: "emulsione-22",
    index: 22,
    filename: "img22.jpg",
    publicPath: "/media/emulsione/img22.jpg",
    legacyPath: "emulsione/img/img22.jpg",
    width: 2560,
    height: 2560,
    alt: "Dark square film print of a river cutting through a blocky forest scene.",
  }),
] as const;

export const emulsioneGallery = createGalleryManifest({
  routeKey: "emulsione",
  legacyFolder: "emulsione",
  images: emulsioneImages,
});
