import { createGalleryImageAsset, createGalleryManifest } from "@/lib/content/builders";

const laWy25Images = [
  createGalleryImageAsset({
    id: "la-wy25-01",
    index: 1,
    filename: "la-venice-skatepark-diptych.jpg",
    publicPath: "/media/la-wy25/la-venice-skatepark-diptych.jpg",
    legacyPath: "Usapostaggio/POST/pentax-2.jpg",
    width: 2000,
    height: 1891,
    alt: "Late-afternoon skaters moving through a concrete bowl at Venice Beach beneath pale coastal light.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-02",
    index: 2,
    filename: "joshua-tree-slow-sign.jpg",
    publicPath: "/media/la-wy25/joshua-tree-slow-sign.jpg",
    legacyPath: "Usapostaggio/POST/pentax-3.jpg",
    width: 2000,
    height: 1845,
    alt: "Weathered SLOW road sign fixed to a tree near Joshua trees on a sandy desert roadside.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-03",
    index: 3,
    filename: "cholla-garden-stop-sign.jpg",
    publicPath: "/media/la-wy25/cholla-garden-stop-sign.jpg",
    legacyPath: "Usapostaggio/POST/pentax-1.jpg",
    width: 1463,
    height: 2048,
    alt: "Red stop sign rising above a Cholla cactus field under dark storm clouds in Joshua Tree.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-04",
    index: 4,
    filename: "flagstaff-motel-corridor.jpg",
    publicPath: "/media/la-wy25/flagstaff-motel-corridor.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-5.jpg",
    width: 1080,
    height: 1166,
    alt: "Soft-focus motel corridor opening onto daylight at the far exit in Flagstaff.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-05",
    index: 5,
    filename: "flagstaff-cinder-hill-road.jpg",
    publicPath: "/media/la-wy25/flagstaff-cinder-hill-road.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-4.jpg",
    width: 1080,
    height: 1166,
    alt: "Dark volcanic cinder slope beside an empty road near Flagstaff under a pale sky.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-06",
    index: 6,
    filename: "sedona-cliff-overlook-bw.jpg",
    publicPath: "/media/la-wy25/sedona-cliff-overlook-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-7.jpg",
    width: 1606,
    height: 2048,
    alt: "Black-and-white view from a Sedona cliff edge looking across the valley toward a mesa.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-07",
    index: 7,
    filename: "sedona-rock-tower-bw.jpg",
    publicPath: "/media/la-wy25/sedona-rock-tower-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-6.jpg",
    width: 1549,
    height: 2048,
    alt: "Black-and-white close view of a steep Sedona rock tower above a scrub-filled drop.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-08",
    index: 8,
    filename: "sedona-cathedral-rock-reflection.jpg",
    publicPath: "/media/la-wy25/sedona-cathedral-rock-reflection.jpg",
    legacyPath: "Usapostaggio/POST/4x5-1.jpg",
    width: 1587,
    height: 2048,
    alt: "Cathedral Rock reflected in a shallow rain pool on red sandstone in Sedona.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-09",
    index: 9,
    filename: "grand-canyon-overlook-bw.jpg",
    publicPath: "/media/la-wy25/grand-canyon-overlook-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-9.jpg",
    width: 1920,
    height: 1642,
    alt: "Black-and-white Grand Canyon overlook framed by twisted branches and scattered pines.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-10",
    index: 10,
    filename: "monument-valley-motel-silhouette.jpg",
    publicPath: "/media/la-wy25/monument-valley-motel-silhouette.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-2.jpg",
    width: 1080,
    height: 1166,
    alt: "Roadside motel sign at sunset with a Monument Valley butte silhouetted in the distance.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-11",
    index: 11,
    filename: "monument-valley-roadside-butte.jpg",
    publicPath: "/media/la-wy25/monument-valley-roadside-butte.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-3.jpg",
    width: 1080,
    height: 1166,
    alt: "A solitary Monument Valley butte rising beside the road under clear morning light.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-12",
    index: 12,
    filename: "monument-valley-wide-desert-bw.jpg",
    publicPath: "/media/la-wy25/monument-valley-wide-desert-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-3.jpg",
    width: 1610,
    height: 2048,
    alt: "Black-and-white desert floor and distant sandstone spires in Monument Valley.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-13",
    index: 13,
    filename: "monument-valley-tree-silhouette-bw.jpg",
    publicPath: "/media/la-wy25/monument-valley-tree-silhouette-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-4.jpg",
    width: 1920,
    height: 1515,
    alt: "Black-and-white leafless tree standing in sand with Monument Valley formations beyond.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-14",
    index: 14,
    filename: "monument-valley-cliff-face-bw.jpg",
    publicPath: "/media/la-wy25/monument-valley-cliff-face-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-5.jpg",
    width: 1604,
    height: 2048,
    alt: "Black-and-white cliff wall and scrub plain inside Monument Valley.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-15",
    index: 15,
    filename: "monument-valley-lone-spire-bw.jpg",
    publicPath: "/media/la-wy25/monument-valley-lone-spire-bw.jpg",
    legacyPath: "Usapostaggio/POST/4x5-2.jpg",
    width: 1595,
    height: 2048,
    alt: "Black-and-white lone sandstone spire rising from dark desert ground in Monument Valley.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-16",
    index: 16,
    filename: "utah-desert-power-lines.jpg",
    publicPath: "/media/la-wy25/utah-desert-power-lines.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-7.jpg",
    width: 1080,
    height: 1166,
    alt: "Power poles crossing a pale Utah desert plain beneath heavy blue storm clouds.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-17",
    index: 17,
    filename: "arches-sandstone-gap.jpg",
    publicPath: "/media/la-wy25/arches-sandstone-gap.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-9.jpg",
    width: 1080,
    height: 1166,
    alt: "White clouds suspended between towering red sandstone walls in Arches.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-18",
    index: 18,
    filename: "arches-twisted-juniper.jpg",
    publicPath: "/media/la-wy25/arches-twisted-juniper.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-1.jpg",
    width: 1080,
    height: 1166,
    alt: "Twisted dead juniper stretching across the frame beneath scattered clouds in Arches.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-19",
    index: 19,
    filename: "arches-red-rock-wall.jpg",
    publicPath: "/media/la-wy25/arches-red-rock-wall.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-10.jpg",
    width: 1080,
    height: 1166,
    alt: "Weathered red sandstone wall and dry grasses under bright cloud breaks in Arches.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-20",
    index: 20,
    filename: "arches-rounded-sandstone.jpg",
    publicPath: "/media/la-wy25/arches-rounded-sandstone.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-8.jpg",
    width: 1080,
    height: 1166,
    alt: "Rounded red sandstone formation rising into a wide blue sky in Arches.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-21",
    index: 21,
    filename: "jackson-antler-motel-neon.jpg",
    publicPath: "/media/la-wy25/jackson-antler-motel-neon.jpg",
    legacyPath: "Usapostaggio/POST/nikon-8.jpg",
    width: 1080,
    height: 1002,
    alt: "Neon Antler Motel sign glowing red at dusk in Jackson, Wyoming.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-22",
    index: 22,
    filename: "jackson-hand-fire-pizza-sign.jpg",
    publicPath: "/media/la-wy25/jackson-hand-fire-pizza-sign.jpg",
    legacyPath: "Usapostaggio/POST/nikon-7.jpg",
    width: 1080,
    height: 1002,
    alt: "Teton Hand Fire Pizza marquee lit in red and white against an evening sky in Jackson.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-23",
    index: 23,
    filename: "wyoming-red-brick-house.jpg",
    publicPath: "/media/la-wy25/wyoming-red-brick-house.jpg",
    legacyPath: "Usapostaggio/POST/hasselblad-6.jpg",
    width: 1080,
    height: 1166,
    alt: "Front view of a red-brick house with white trim and overgrown shrubs in Wyoming.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-24",
    index: 24,
    filename: "wyoming-vintage-gas-pump.jpg",
    publicPath: "/media/la-wy25/wyoming-vintage-gas-pump.jpg",
    legacyPath: "Usapostaggio/POST/nikon-3.jpg",
    width: 1080,
    height: 1164,
    alt: "Vintage orange-and-white gas pump beside a giraffe cutout on a yellow wall in Wyoming.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-25",
    index: 25,
    filename: "wyoming-horse-mural-storefront.jpg",
    publicPath: "/media/la-wy25/wyoming-horse-mural-storefront.jpg",
    legacyPath: "Usapostaggio/POST/nikon-2.jpg",
    width: 1080,
    height: 1002,
    alt: "Weathered horse mural wrapping around a yellow storefront beneath a metal awning in Wyoming.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-26",
    index: 26,
    filename: "wyoming-red-gmc-closeup.jpg",
    publicPath: "/media/la-wy25/wyoming-red-gmc-closeup.jpg",
    legacyPath: "Usapostaggio/POST/nikon-12.jpg",
    width: 1080,
    height: 1002,
    alt: "Close crop of a red GMC truck bumper and front wheel in afternoon light.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-27",
    index: 27,
    filename: "wyoming-red-vw-plate.jpg",
    publicPath: "/media/la-wy25/wyoming-red-vw-plate.jpg",
    legacyPath: "Usapostaggio/POST/nikon-5.jpg",
    width: 1080,
    height: 1164,
    alt: "Front corner of a red Volkswagen with a Wyoming plate and autumn leaves scattered on the road.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-28",
    index: 28,
    filename: "wyoming-blue-chevy-plate.jpg",
    publicPath: "/media/la-wy25/wyoming-blue-chevy-plate.jpg",
    legacyPath: "Usapostaggio/POST/nikon-13.jpg",
    width: 1080,
    height: 1002,
    alt: "Blue Chevrolet parked on a small-town Wyoming street beneath midday sun.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-29",
    index: 29,
    filename: "wyoming-barn-golden-field.jpg",
    publicPath: "/media/la-wy25/wyoming-barn-golden-field.jpg",
    legacyPath: "Usapostaggio/POST/nikon-14.jpg",
    width: 1080,
    height: 1164,
    alt: "Dark barn beside a winding pale road across a golden Wyoming field.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-30",
    index: 30,
    filename: "teton-road-mirror.jpg",
    publicPath: "/media/la-wy25/teton-road-mirror.jpg",
    legacyPath: "Usapostaggio/POST/nikon-6.jpg",
    width: 1080,
    height: 1002,
    alt: "Snowy mountains and an empty highway reflected in a car side mirror near the Tetons.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-31",
    index: 31,
    filename: "wyoming-meadow-figure.jpg",
    publicPath: "/media/la-wy25/wyoming-meadow-figure.jpg",
    legacyPath: "Usapostaggio/POST/nikon-9.jpg",
    width: 1080,
    height: 1164,
    alt: "Solitary figure in a yellow hat standing in a pale meadow below mist and autumn trees.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-32",
    index: 32,
    filename: "jackson-deer-between-cabins.jpg",
    publicPath: "/media/la-wy25/jackson-deer-between-cabins.jpg",
    legacyPath: "Usapostaggio/POST/nikon-4.jpg",
    width: 1080,
    height: 1002,
    alt: "Two deer standing between log cabins in Jackson as autumn leaves cover the grass.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-33",
    index: 33,
    filename: "wyoming-river-overlook.jpg",
    publicPath: "/media/la-wy25/wyoming-river-overlook.jpg",
    legacyPath: "Usapostaggio/POST/nikon-11.jpg",
    width: 1080,
    height: 1164,
    alt: "High view over a winding river cutting through open grassland in Wyoming.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-34",
    index: 34,
    filename: "wyoming-two-trees-hillside.jpg",
    publicPath: "/media/la-wy25/wyoming-two-trees-hillside.jpg",
    legacyPath: "Usapostaggio/POST/nikon-10.jpg",
    width: 1080,
    height: 1002,
    alt: "Two isolated trees standing on a dry Wyoming hillside with layered mountains beyond.",
  }),
  createGalleryImageAsset({
    id: "la-wy25-35",
    index: 35,
    filename: "grand-teton-autumn-slope.jpg",
    publicPath: "/media/la-wy25/grand-teton-autumn-slope.jpg",
    legacyPath: "Usapostaggio/POST/nikon-1.jpg",
    width: 1080,
    height: 1002,
    alt: "Sunlit autumn slope leading up to the jagged Grand Teton peaks.",
  }),
] as const;

export const laWy25Gallery = createGalleryManifest({
  routeKey: "la-wy25",
  legacyFolder: "la-wy25",
  images: laWy25Images,
});
