import { createGalleryImageAsset, createGalleryManifest } from "@/lib/content/builders";

const radiciImages = [
  createGalleryImageAsset({
    id: "radici-01",
    index: 1,
    filename: "img1.jpg",
    publicPath: "/media/radici/img1.jpg",
    legacyPath: "radici/img/img1.jpg",
    width: 1920,
    height: 1283,
    alt: "Figure seen from behind facing ruined stone buildings in a leaf-covered clearing.",
  }),
  createGalleryImageAsset({
    id: "radici-02",
    index: 2,
    filename: "img2.jpg",
    publicPath: "/media/radici/img2.jpg",
    legacyPath: "radici/img/img2.jpg",
    width: 1282,
    height: 1920,
    alt: "Leafless trees framing a stone house on a dim hillside.",
  }),
  createGalleryImageAsset({
    id: "radici-03",
    index: 3,
    filename: "img3.jpg",
    publicPath: "/media/radici/img3.jpg",
    legacyPath: "radici/img/img3.jpg",
    width: 1282,
    height: 1920,
    alt: "Tall stone facade with a dark doorway and a small upper window.",
  }),
  createGalleryImageAsset({
    id: "radici-04",
    index: 4,
    filename: "img4.jpg",
    publicPath: "/media/radici/img4.jpg",
    legacyPath: "radici/img/img4.jpg",
    width: 1283,
    height: 1920,
    alt: "Overgrown stone window opening crossed by a leaning wooden beam.",
  }),
  createGalleryImageAsset({
    id: "radici-05",
    index: 5,
    filename: "img5.jpg",
    publicPath: "/media/radici/img5.jpg",
    legacyPath: "radici/img/img5.jpg",
    width: 1282,
    height: 1920,
    alt: "Corner of an abandoned stone building in a wooded clearing.",
  }),
  createGalleryImageAsset({
    id: "radici-06",
    index: 6,
    filename: "img6.jpg",
    publicPath: "/media/radici/img6.jpg",
    legacyPath: "radici/img/img6.jpg",
    width: 1920,
    height: 1282,
    alt: "Ivy-covered stone arch and wall ruins in a shadowed woodland.",
  }),
  createGalleryImageAsset({
    id: "radici-07",
    index: 7,
    filename: "img7.jpg",
    publicPath: "/media/radici/img7.jpg",
    legacyPath: "radici/img/img7.jpg",
    width: 1920,
    height: 1282,
    alt: "Two figures among bare trees near ruined buildings at dusk.",
  }),
  createGalleryImageAsset({
    id: "radici-08",
    index: 8,
    filename: "img8.jpg",
    publicPath: "/media/radici/img8.jpg",
    legacyPath: "radici/img/img8.jpg",
    width: 1920,
    height: 1282,
    alt: "Two figures walking toward a stone house in a grassy clearing.",
  }),
  createGalleryImageAsset({
    id: "radici-09",
    index: 9,
    filename: "img9.jpg",
    publicPath: "/media/radici/img9.jpg",
    legacyPath: "radici/img/img9.jpg",
    width: 1920,
    height: 1282,
    alt: "Figure facing a chapel wall marked by a dark cross.",
  }),
  createGalleryImageAsset({
    id: "radici-10",
    index: 10,
    filename: "img10.jpg",
    publicPath: "/media/radici/img10.jpg",
    legacyPath: "radici/img/img10.jpg",
    width: 1920,
    height: 1282,
    alt: "Close view of a mossy stone house entrance beneath a low roof.",
  }),
  createGalleryImageAsset({
    id: "radici-11",
    index: 11,
    filename: "img11.jpg",
    publicPath: "/media/radici/img11.jpg",
    legacyPath: "radici/img/img11.jpg",
    width: 1920,
    height: 1282,
    alt: "Roots and rubble filling the interior of a roofless stone ruin.",
  }),
  createGalleryImageAsset({
    id: "radici-12",
    index: 12,
    filename: "img12.jpg",
    publicPath: "/media/radici/img12.jpg",
    legacyPath: "radici/img/img12.jpg",
    width: 1920,
    height: 1282,
    alt: "Distant figure in red standing among trees and ruined stone walls in a dark forest clearing.",
  }),
  createGalleryImageAsset({
    id: "radici-13",
    index: 13,
    filename: "img13.jpg",
    publicPath: "/media/radici/img13.jpg",
    legacyPath: "radici/img/img13.jpg",
    width: 1282,
    height: 1920,
    alt: "Exposed tree roots gripping a steep forest slope.",
  }),
  createGalleryImageAsset({
    id: "radici-14",
    index: 14,
    filename: "img14.jpg",
    publicPath: "/media/radici/img14.jpg",
    legacyPath: "radici/img/img14.jpg",
    width: 1282,
    height: 1920,
    alt: "Vine-covered window opening with a long branch leaning outward.",
  }),
  createGalleryImageAsset({
    id: "radici-15",
    index: 15,
    filename: "img15.jpg",
    publicPath: "/media/radici/img15.jpg",
    legacyPath: "radici/img/img15.jpg",
    width: 1282,
    height: 1920,
    alt: "Rectangular window cut into a stone wall, revealing woodland beyond.",
  }),
  createGalleryImageAsset({
    id: "radici-16",
    index: 16,
    filename: "img16.jpg",
    publicPath: "/media/radici/img16.jpg",
    legacyPath: "radici/img/img16.jpg",
    width: 1283,
    height: 1920,
    alt: "Gridded window overtaken by vines and roots inside a dark ruin.",
  }),
  createGalleryImageAsset({
    id: "radici-17",
    index: 17,
    filename: "img17.jpg",
    publicPath: "/media/radici/img17.jpg",
    legacyPath: "radici/img/img17.jpg",
    width: 1920,
    height: 1282,
    alt: "Solitary figure standing near a pale stone wall beneath arching trees.",
  }),
  createGalleryImageAsset({
    id: "radici-18",
    index: 18,
    filename: "img18.jpg",
    publicPath: "/media/radici/img18.jpg",
    legacyPath: "radici/img/img18.jpg",
    width: 1282,
    height: 1920,
    alt: "Massive tree trunk rising from mossy boulders in fading light.",
  }),
  createGalleryImageAsset({
    id: "radici-19",
    index: 19,
    filename: "img19.jpg",
    publicPath: "/media/radici/img19.jpg",
    legacyPath: "radici/img/img19.jpg",
    width: 1282,
    height: 1920,
    alt: "Stone outbuilding beneath a leafless tree and a cloudy sky.",
  }),
  createGalleryImageAsset({
    id: "radici-20",
    index: 20,
    filename: "img20.jpg",
    publicPath: "/media/radici/img20.jpg",
    legacyPath: "radici/img/img20.jpg",
    width: 1282,
    height: 1920,
    alt: "Narrow forest path leading between crumbling stone walls.",
  }),
  createGalleryImageAsset({
    id: "radici-21",
    index: 21,
    filename: "img21.jpg",
    publicPath: "/media/radici/img21.jpg",
    legacyPath: "radici/img/img21.jpg",
    width: 1282,
    height: 1920,
    alt: "Twisted vines covering a doorway in a dark stone facade.",
  }),
] as const;

export const radiciGallery = createGalleryManifest({
  routeKey: "radici",
  legacyFolder: "radici",
  images: radiciImages,
});
